#!/bin/bash
usage() {
	echo "Usage: $0 [all | vim | tmux]"
}
if [  $# -le 0 ]
then
	usage
	exit 1
fi
if [[ ( $# == "--help") ||  $# == "-h" ]]
then
	usage
	exit 0
fi

DOTFILES="`dirname \"$0\"`"
DOTFILES="`( cd \"$DOTFILES\" && pwd )`"

install_vim() {
	# Download plugins
	echo "Downloading vim plugins..."
	mkdir -p .vim/bundle
	cd .vim/bundle
	while read p && [[ -n "$p" ]]; do
		git clone $p
	done < "$DOTFILES/.vim/bundle.list"

	# Remove existing configuration
	rm -rf ~/.vim ~/.vimrc

	# Write new configuration
	mkdir ~/.vim
	rsync -r $DOTFILES/.vim/ ~/.vim/
	rsync -r $DOTFILES/.vimrc ~/.vimrc
}
install_tmux() {
	# Remove existing configuration
	rm -rf ~/.tmux.conf

	# Write new configuration
	rsync -r $DOTFILES/.tmux.conf ~/.tmux.conf
}

case "$1" in
	all)
		install_vim
		install_tmux
		;;
	vim)
		install_vim
		;;
	tmux)
		install_tmux
		;;
	*)
		usage
		exit 1
esac
